### ISSUE TITLE
Disabling drawn polygons on a sample scene

### ISSUE THREAD

**Issue by maotisimo** [dmbfm/unity-ar-gps-location-issues#102]
Hello! Thank you very much for your work. 

I want to use the sample from the ARLocation Path Line Render, but I am not able to remove the yellow polygons that are drawn around the origin, nor the green plane that appears. Can you help me please? I don't know from which object or script they are launched and even though I try to disable some, I can't find it.

[Example.mp4.zip](https://github.com/dmbfm/unity-ar-gps-location-issues/files/5683633/Example.mp4.zip)

**Comment by dmbfm** [comment]
The yellow polygons are the plane visualization prefabs. Just set the Prefab to None in the AR Plane Manager component to remove it.

The green plane I'm not sure, but I think you have a GameObject with a line-renderer that is not being used on your scene.

**Comment by maotisimo** [comment]
Thank you. I've done as you wrote and it works.
