### ISSUE TITLE
Cant see the 'AR+GPS -> Create Basic Scene Structure' option in the hierarchy 

### ISSUE THREAD

**Issue by dan-howitt** [dmbfm/unity-ar-gps-location-issues#106]
**Describe the bug**
I recently purchased your AR+GPS Location asset from the Unity3D asset store and I am having problems immediately.  I tried following the quickstart guide on your website.  I've imported AR Foundation, AR Core XR Plugin and the AR Kit XR Plugin and then finally the AR+GPS location asset.  I removed the main camera and its the next step that is not working.

'Right-click on the Hierarchy and go to AR+GPS -> Create Basic Scene Structure' - I dont see the AR+GPS option in the menu when I right click, i can see the ARLocation folder in the asset folder.

I've tried the same steps in an existing project that I was hoping to use this for (but with a new scene) and I tried creating a new project but the same result.

I get the following errors in the console - I dont know if this will help figure out what is wrong.:

The editor layout could not be fully loaded, this can happen when the layout contains EditorWindows not available in this project
UnityEditor.WindowLayout:LoadDefaultWindowPreferences()

Library\PackageCache\com.unity.xr.management@3.2.17\Editor\XRGeneralBuildProcessor.cs(39,52): error CS0117: 'BuildPipeline' does not contain a definition for 'GetBuildTargetName'

Library\PackageCache\com.unity.xr.management@3.2.17\Editor\XRGeneralBuildProcessor.cs(86,52): error CS0117: 'BuildPipeline' does not contain a definition for 'GetBuildTargetName'

Can't calculate tangents, because mesh 'Widget' doesn't contain normals.

Warnings during import of AudioClip Assets/ARLocation/Sounds/jet.mp3
FSBTool WARNING: This source file was truncated. Length reported 23311872 bytes, length decoded = 23286272 bytes.

I sent you an email and then realised I should submit bugs here!

**Desktop (please complete the following information):**
 - OS: Win10
 - Unity Version: 2019.4.13f1

**Comment by dmbfm** [comment]
Which version of ARFoundation are you using? Could be related to this: https://answers.unity.com/questions/1795233/unity-hdrp-giving-error.html

If you can, reply to support@unity-ar-gps-location.com, which is our main support channel now. 

You can send the project in a .zip file and I can take a look at it as well. 

Thanks!

**Comment by dan-howitt** [comment]
I tried what you suggested and worked perfect - read the email before I checked here. so i've just sent you an email.  Thank you very much!

Dan
