### ISSUE TITLE
Still struggling to use the guide for the Create Basic Scene Structure.

### ISSUE THREAD

**Issue by dan-howitt** [dmbfm/unity-ar-gps-location-issues#108]
**Describe the bug**
I had an issue with the version of ARCore XR Plugin causing errors but you sent me a link which advised to use an older version and that seemed to work however I am having more problems, would really appreciate if you can help me out.

I followed the guide and it seemed ok - managed to add the basic scene structure but when I go to build settings and click build I get the following errors:

BuildFailedException: ARCore Required apps require a minimum SDK version of 24. Currently set to AndroidApiLevel19
UnityEditor.XR.ARCore.ARCorePreprocessBuild.EnsureMinSdkVersion () (at Library/PackageCache/com.unity.xr.arcore@2.1.16/Editor/ARCoreBuildProcessor.cs:110)
UnityEditor.XR.ARCore.ARCorePreprocessBuild.OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Library/PackageCache/com.unity.xr.arcore@2.1.16/Editor/ARCoreBuildProcessor.cs:34)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass15_0.<OnBuildPreProcess>b__1 (UnityEditor.Build.IPreprocessBuildWithReport bpp) (at <bef6d2fbef1348939b77102b4cf6a6e6>:0)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at <bef6d2fbef1348939b77102b4cf6a6e6>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Error building Player: BuildFailedException: ARCore Required apps require a minimum SDK version of 24. Currently set to AndroidApiLevel19

Build completed with a result of 'Failed' in 0 seconds (121 ms)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002bf] in <bef6d2fbef1348939b77102b4cf6a6e6>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <bef6d2fbef1348939b77102b4cf6a6e6>:0 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I tried to resolve this by going into player settings/other settings and changing the minimum api level from 19 to 24 but this just caused the following errors:

BuildFailedException: You have enabled the Vulkan graphics API, which is not supported by ARCore.
UnityEditor.XR.ARCore.ARCorePreprocessBuild.EnsureOnlyOpenGLES3IsUsed () (at Library/PackageCache/com.unity.xr.arcore@2.1.16/Editor/ARCoreBuildProcessor.cs:134)
UnityEditor.XR.ARCore.ARCorePreprocessBuild.OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Library/PackageCache/com.unity.xr.arcore@2.1.16/Editor/ARCoreBuildProcessor.cs:35)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass15_0.<OnBuildPreProcess>b__1 (UnityEditor.Build.IPreprocessBuildWithReport bpp) (at <bef6d2fbef1348939b77102b4cf6a6e6>:0)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at <bef6d2fbef1348939b77102b4cf6a6e6>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Error building Player: BuildFailedException: You have enabled the Vulkan graphics API, which is not supported by ARCore.

Build completed with a result of 'Failed' in 0 seconds (104 ms)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002bf] in <bef6d2fbef1348939b77102b4cf6a6e6>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <bef6d2fbef1348939b77102b4cf6a6e6>:0 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Failed getting available Android API levels. Could not find Android SDK Tools.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I tried to fix it by removing Vulkan graphics API but it just more errors.

I honestly dont know what im doing im trying to figure it out, I appreciate this might not be a bug with your asset but if you could help I would really appreciate it!

Thank you!
Dan Howitt

**Screenshots and Videos**
If applicable, add screenshots and videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Unity Version: 2019.4.19F

**Smartphone (please complete the following information):**
 - Device: android

**Additional context**

**Comment by dmbfm** [comment]
Well, what errors you got after disabling Vulkan?

**Comment by dmbfm** [comment]
Hi!,

Does this only happen if our Asset is imported?

If not this is not an issue with our asset, but with your Unity installation. There is an error message mentioning 
the Android SDK Tools could not be found, so maybe this is the issue? Maybe you can try reinstalling Unity, making
sure that the Android SDK is installed in the process?

I would advise you to reach out to Unity for further support on this. 

Our main support channel is support@unity-ar-gps-location.com. You will probably get a faster response by reaching out to us there.

Thanks,

**Comment by dan-howitt** [comment]
Hi
I think i've fixed it now.  I just continued with errors and did a bunch of updates - basically followed what it was complaining about.  Im in unfamiliar territory is all and it just felt like it wasnt getting any where.  Thank you for messaging back so quickly and thank you for the advice and help!

Dan Howitt
