### ISSUE TITLE
Object NOT showing - AR + GPS Location Plugin

### ISSUE THREAD

**Issue by dakpax** [dmbfm/unity-ar-gps-location-issues#20]
Hey Daniel,

I wrote you an email yesterday as I have not managed to make the plugin work.

I tried following the documentation and youtube tutorials exactly and it seems quite straight forward but it does NOT work.

I also tried some of the samples you have and still does not work.

I do believe that it manages to find the location as I get the Origin Gyzmo but not the object.

Can you please check your mail for more info and get back to me.

I am working on a project and my colleagues waiting to see it work for our project.

Thank you and cant wait to have it working.

Kevinelkha@gmail.com

**Comment by dmbfm** [comment]
Ok, I will answer your email then. Thanks!
