### ISSUE TITLE
AR Floor Shadow

### ISSUE THREAD

**Issue by robertocorrales** [dmbfm/unity-ar-gps-location-issues#23]
After following the main tutorial when I add the AR Floor I don't see the shadow.
Not even in the Editor...
What could I been doing wrong??
Thanks!

 - OS: MAC
 - Unity Version: 219.2.1f1
 - Device: iPhone XS MAX
 - OS: 13.2.3

![Screenshot 2019-12-11 at 16 50 07](https://user-images.githubusercontent.com/4540186/70636969-ba70fc80-1c36-11ea-9426-d975f46644a6.png)

**Comment by dmbfm** [comment]
Maybe the quality settings in your project are disabling the shadows? I had that happen to me a few times. 

Inside the editor it wont show the shadows, it is a shader that only works in runtime.

**Comment by robertocorrales** [comment]
mmmmm I don't know... quality setting seem to be ok...

![Screenshot 2019-12-12 at 10 42 56](https://user-images.githubusercontent.com/4540186/70704637-b4305e00-1cd2-11ea-8744-991ef72f1a66.png)

But in runtime , I can see the logo shadow over a regular plane but not over the AR Floor...

![IMG_2598](https://user-images.githubusercontent.com/4540186/70704697-d75b0d80-1cd2-11ea-954d-e0f422a5f131.PNG)

**Comment by dmbfm** [comment]
Another possibility is that the AR Floor is not being placed under the objects then. Where is the AR floor in the scene? Can you send a screenshot of the scene's hierarchy?

**Comment by robertocorrales** [comment]
Yes sure. It's in the first comment. But here you have it again.
![Screenshot 2019-12-11 at 16 50 07](https://user-images.githubusercontent.com/4540186/70907042-17d6c600-2008-11ea-905d-bbeace07520e.png)

Thanks

**Comment by dmbfm** [comment]
Can you send me the project folder in a .zip file to my email (daniel.mbfm@gmail.com) so I can take a look at it? 

Thanks

**Comment by robertocorrales** [comment]
Yes sure. I sent it yesterday.
Thanks

**Comment by dmbfm** [comment]
After looking into it, it seems there is an issue with AR Floor on Unity 2019.2.

But it easy to fix it so it works. Just change the RenderQueue to "Geometry" on the ARFLoor material:

![image](https://user-images.githubusercontent.com/8743306/71143428-4ff12b00-21f9-11ea-8280-02c86a21c7df.png)

I will change this for the next version.  Let me know if it works.

Thanks!

**Comment by robertocorrales** [comment]
Hi Dani. Thanks! It works!
But the shadows are really hard. Is there a way to soft them up e little?

![IMG_2607](https://user-images.githubusercontent.com/4540186/71167349-d424cc00-2254-11ea-9504-87538d2dc435.PNG)

**Comment by dmbfm** [comment]
That will depend on your project settings and on the settings on the light components on the scene (https://docs.unity3d.com/Manual/ShadowOverview.html).
