### ISSUE TITLE
MaxNumberOfLocationUpdates and Accuracy

### ISSUE THREAD

**Issue by robertocorrales** [dmbfm/unity-ar-gps-location-issues#29]
Hi there.
Does it make sense if I place an object 100m away for example and I set MaxNumberOfLocationUpdates to 0 so its always updating the location and then when I'm close (like 30m for example) I set it back to 1 so it stops "moving"? I'm trying to get the best accuracy as possible while the user is far from the point but when it's close to it stop the Updates so the user won't see it moving.

Does it make sense?

Thanks a lot!!!

**Comment by dmbfm** [comment]
Hi!,

Yes, I think it does, and that's what I would do as well. 

In fact you can change all filtering settings when it is far away to increase the accuracy I think, that should work well.

**Comment by robertocorrales** [comment]
I don’t understand what do you men by “all the filtering “ Could you give me an example of the set up while far away and when close to the point?

**Comment by dmbfm** [comment]
Sorry, my mistake actually, some of these settings would be in the location provider (like  "Time Between Updates")

We could, add a feature so that  you could choose to use the raw data if you want to, in situations where the objects are far away.

**Comment by robertocorrales** [comment]
Understood. Thanks.
