### ISSUE TITLE
Switching between scenes in Unity

### ISSUE THREAD

**Issue by JcFractal** [dmbfm/unity-ar-gps-location-issues#3]
Hi I'm really enjoying the asset, great work!
 I have a question, I made 2 scenes in my project: Main menu and ARscene, when I first 
loaded  the ARscene from Mainmenu, the geo location worked perfect, but when I pressed a back button that took me back to Mainmenu and then came back to the ARscene, the zombie appeared next to me instead of its gps location and my other AR elements were not showing up. I tried a few times going back and forth between the scenes and the gps didn't work anymore. How do I set it up so that when I switch scenes the gps activates again correctly.

Thanks you 
JcFractal

**Comment by JcFractal** [comment]
Hi! ok I just tested it with 2 scenes and it works!! I switched back and forth and it continues to work!
Thank you so much! great asset! brilliant work!

JcFractal

**Comment by dmbfm** [comment]
Thanks for your feedback! Closing the issue for now 👍
