### ISSUE TITLE
Weird vibration... 

### ISSUE THREAD

**Issue by robertocorrales** [dmbfm/unity-ar-gps-location-issues#30]
iPhone X iOS 13.3
Unity 2019.2.1f1

Hi there, I have a problem (suddenly) when testing my app in-site.

Do you know why this could be happening? Have you experienced this before?
Video attached.

Thanks

[IMG_2754.zip](https://github.com/dmbfm/unity-ar-gps-location-issues/files/4108247/IMG_2754.zip)

**Comment by robertocorrales** [comment]
One detail. I have different scenes with AR. The user finds one object. Jumps to a Scene with text, the goes to another scene with AR+GPS. This happens 5 times.
Do I need to stop and restart something? The first one usually works fine...
Thanks

**Comment by dmbfm** [comment]
Maybe there can be an issue... it would be better to make the AR and AR+GPS part of the scene persistent with a DontDestroyOnLoad call...

In any case, is it possible that you send me the project to daniel.mbfm@gmail.com so I can take a look and try to reproduce the issue here? Thanks,

**Comment by robertocorrales** [comment]
Hi It was something else. I'll close de issue.
Thanks!!!
