### ISSUE TITLE
"App will not work on iOS 10+"

### ISSUE THREAD

**Issue by k7n4n5t3w4rt** [dmbfm/unity-ar-gps-location-issues#34]
**Describe the bug**

Building for iOS, the following warning appears in the console:

> LocationService class is used but Locations Usage Description is empty. App will not work on iOS 10+.
>UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:123)

**Screenshots and Videos**

<img width="1392" alt="Screen Shot 2020-02-10 at 10 47 55 pm" src="https://user-images.githubusercontent.com/358035/74147500-778fcd00-4c57-11ea-91bb-02429f15f066.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.6 (18G1012)
 - Unity Version: 2019.3.0f6

**Smartphone (please complete the following information):**
 - Device: iPad Pro (12.9-inch) (2nd generation)
 - OS: iOS
 - Version: 13.3.1

**Additional context**

The objects inside the "GPS Stage Object" don't appear when the app build runs on the iPad. The app works as expected on an Android Pixel2 phone.

**Comment by dmbfm** [comment]
What the message is saying actually is that you need the "Location Usade Descriptor" on the player settings for iOS. Also, you need to set iOS version to 11 or higher.

As for the iPad, usually iPads don't use cellular networks, and no GPS, so probably this wont work correctly on iPads. Does your iPad has celular network (3G/4G etc)?

**Comment by k7n4n5t3w4rt** [comment]
Aha! Sorry for missing that. Addid a value for the "Location Usade Descriptor" on the player settings for iOS got rid of the error.

There's no SIM card in this iPad so no cellular network. GoogleMaps works though... I'll try it on an iPhone.

Many thanks for your speedy and helpful response.
