### ISSUE TITLE
Limit on distance from camera/user to gps coordinate locations

### ISSUE THREAD

**Issue by pixeldustlabs** [dmbfm/unity-ar-gps-location-issues#36]
Is there a limit to how far the camera/user can track a gps coordinate? Only coordinates in range of about half a mile radius roughly are able to track so far and show up just fine, but for our purpose we need to be able to track certain locations more than a mile maybe 20 miles. Is this possible? Thank you!

**Comment by dmbfm** [comment]
You need objects that are far away to be displayed on the screen?

The positions of all the objects are calculated. To make them actually show up on the screen,
you need to change the camera's far clipping plane distance:

![image](https://user-images.githubusercontent.com/8743306/74488457-08a5b480-4ea1-11ea-9ceb-7627e52d1974.png)

So, if you need 20miles, you can set this to 32186.9 (the same distance in meters).

Let me know if this works.

**Comment by pixeldustlabs** [comment]
thank you for this, this worked just fine and works much better when im outside. tested it from various locations. However i lost my vuforia background video feed  (bg=black) and has to do with the now extended camera clipping plane, video feed works again if i restore the clipping plane to 2000 that was earlier. Any workaround for this on your plugin side? thanks!!

**Comment by pixeldustlabs** [comment]
by the way i was able to resolve this issue of the camera showing black by increasing near clipping plane to 10 from .05, so near 10 and far 62000! So compensating on the clipping plane range i guess so the phone gpu can handle it better.

**Comment by dmbfm** [comment]
Yes, I also had that issue of the near plane with Vuforia! Glad you managed to make it work. Thanks
