### ISSUE TITLE
Problem with new android version

### ISSUE THREAD

**Issue by santeri13** [dmbfm/unity-ar-gps-location-issues#38]
Week ago I download new android version on phone and when I continue to work with my project I do not see 3d models on my phone on locations.

**Comment by dmbfm** [comment]
Hi,

Which unity version and device model are you using?

Are you using Vuforia or ARFoundation?

You upgraded from which version of the asset to the latest?

When you run the app, you get any errors on the Android logcat?

If you can send me the project folder in a .zip file either here or to the email daniel.mbfm@gmail.com. 

Thanks.
