### ISSUE TITLE
Example of GetGameObjectPositionForLocation()

### ISSUE THREAD

**Issue by immersionfx** [dmbfm/unity-ar-gps-location-issues#39]
Hello,

Say we have a gameObject placed somewhere in the scene. What is the way to get its GPS location data? Is this what GetGameObjectPositionForLocation() is for? Can you provide a scripting example of:
```
GetGameObjectPositionForLocation(
   Transform arLocationRoot,
   Vector3 userPosition,
   Location userLocation,
   Location objectLocation,
   bool heightIsRelative ) 
```

I am trying to get GPS position for an object in front of me but I can't figure out what value is required for the _Location objectLocation_ parameter (assuming that _userLocation = locationProvider.CurrentLocation_).

Much appreciated!

**Comment by dmbfm** [comment]
Hi,

If you want the GPS location of an object you placed, you can just use the `Location` property of the `PlaceAtLocation` component (https://docs.unity-ar-gps-location.com/api/html/class_a_r_location_1_1_place_at_location.html).

It will return a `Location` object (https://docs.unity-ar-gps-location.com/api/html/class_a_r_location_1_1_location.html).

So, for instance:

```
var placeAtLocation = someGameObject.GetComponent<PlaceAtLocation>();
var loc = placeAtLocation.Location;
var latitude = loc.Latitude;
var longitude = loc.Longitude;
```

**Comment by immersionfx** [comment]
Hi again, 

well, your code will give me the GPS location that I have set **manually** on the PlaceAtLocation script on someGameObject. But what if I haven't set any value? Basically I want the _actual_ GPS location of someGameObject. 

I know I get the camera's _actual_ GPS location with the ARLocationProvider but I can't have an ARLocationProvider in every object in the scene to do the same, right?

So, I assumed that the GetGameObjectPositionForLocation() would give me an object's _actual_ GPS location (is that right?) but I can't figure out what value is required for the _Location objectLocation_ parameter.

**Comment by dmbfm** [comment]
I'm not sure I understand what you mean. The object's GPS location, which you set manually, never changes. Only the device's location is updated. 

What changes is the object's position in the scene, which you can easily get via `transform.position` or `transform.localPosition`.

**Comment by immersionfx** [comment]
So, going back to my original question, what is the GetGameObjectPositionForLocation() function for? And why do I need to pass it the objectLocation's Location (and not world coordinates) data if _THIS_ is what the function returns?

```
Location.GetGameObjectPositionForLocation (
                        Transform arLocationRoot,
                        Vector3 userPosition,
                        Location userLocation,
                        Location objectLocation,
                        bool heightIsRelative )
```

**Comment by dmbfm** [comment]
This function is used internally to calculate the object's position in the scene. It's not really very useful for you to call it. Given the user and object's location it will give the objects position in the scene.  

This will be the scene value you will get in `transform.localPosition` later. 

Again, I'm not sure what you need. The object's GPS location is the one you set, it never changes. The only thing that changes is the object's position in the scene.

**Comment by immersionfx** [comment]
Ah, I guess it should be called GetGameObjectPosition**From**Location, then!
Thanks for all your answers.
