### ISSUE TITLE
Camera is not opening in device

### ISSUE THREAD

**Issue by saifajath** [dmbfm/unity-ar-gps-location-issues#40]
App does not asks camera permission.
I enabled camera permission manually but not working.
It always shows black screen. I am using AR Core and testing on supported device.

Device: Xiomi Note 7S
OS: Android
Version 8.1.0

**Comment by dmbfm** [comment]
Hi,

Is the AR Core XR plugin installed from the package manager window?

**Comment by saifajath** [comment]
Thanks @dmbfm 
Now its Working. AR Core XR Plugin was missing.
