### ISSUE TITLE
PlaceAtLocation/Hotspot does not work correctly

### ISSUE THREAD

**Issue by NouhaBsn** [dmbfm/unity-ar-gps-location-issues#45]
The 3dObject that I want to place is placed at the wrong coordinates(so far from the location that I entered).

**Desktop**
 - OS: MacOs
 - Unity Version: 2019.25f1

**Smartphone**
 - Device: Xiaomi Redmi Note 8 pro
 - OS: android
 - Version 9

**Comment by dmbfm** [comment]
How for from the location would you say it its?

Can you:
- Enable the "Debug Mode" on the "PlaceAtLocation" component
- Place the "ARLocationInfo" prefab on the scene
- If you can, create a screen recording showing the issue

Thanks!

**Comment by NouhaBsn** [comment]
![image](https://user-images.githubusercontent.com/36163092/77357658-ccd7f780-6d48-11ea-8462-aa7282324141.png)



> How for from the location would you say it its?
> 
> Can you:
> 
> * Enable the "Debug Mode" on the "PlaceAtLocation" component
> * Place the "ARLocationInfo" prefab on the scene
> * If you can, create a screen recording showing the issue
> 
> Thanks!

**Comment by dmbfm** [comment]
It show you are more than 24km meters from the object. 

This is too large to be an error from the GPS data or the algorithms. Maybe the coordinate
has a typo?

How far are you from the location?

**Comment by NouhaBsn** [comment]
> It show you are more than 24km meters from the object.
> 
> This is too large to be an error from the GPS data or the algorithms. Maybe the coordinate
> has a typo?
> 
> How far are you from the location?

Thanks for your reply.
I found what was wrong. I was using a much higher gps accuracy.
Can you please tell me In which file I can control the accuracy that is set?

**Comment by dmbfm** [comment]
On the "ARLocationProvider" component (https://docs.unity-ar-gps-location.com/guide/#arlocationprovider) there is a `Accuracy Radius` property. 

If you set it to 10, for instance, it will only accept measurements which have an accuracy of 10m or better. So, the lower you set it, it will reject more measurements.

**Comment by NouhaBsn** [comment]
> On the "ARLocationProvider" component (https://docs.unity-ar-gps-location.com/guide/#arlocationprovider) there is a `Accuracy Radius` property.
> 
> If you set it to 10, for instance, it will only accept measurements which have an accuracy of 10m or better. So, the lower you set it, it will reject more measurements.

Thank you
