### ISSUE TITLE
ARLocation 3D text scene - distance and line distance settings

### ISSUE THREAD

**Issue by ptycharly** [dmbfm/unity-ar-gps-location-issues#47]
Hi ! 
I am discovering the different possibilities offered by AR+GPS and I am very happy with it.

I tested the ARLocation 3D text scene on my smart phone. The POI I set up appears well. Two elements are also displayed: the distance separating each POI from the smartphone position, and a pink line showing this distance. I wish these two items would not be displayed. I searched through all the scripts but I couldn't find where to change these parameters.

Can you help me?

Thank you

**Desktop (please complete the following information):**
 - OS: win 10
 - Unity Version: 2019 3.6f1

**Smartphone (please complete the following information):**
 - Device: samsung A6
 - OS: pie

**Comment by ptycharly** [comment]
Hi, I just figured it out. 
Sorry for the inconvenience.!

**Comment by dmbfm** [comment]
Glad to hear! Closing for now
