### ISSUE TITLE
Map behaves strange in Totem-test

### ISSUE THREAD

**Issue by Dweeh** [dmbfm/unity-ar-gps-location-issues#52]
Hello!

I downloaded the totem test-version on PlayStore.

When I try to locate where I live to place out some totems the map behaves weird. 

When I scale I briefly get a black image with white lines and then end up a bit from where I was - I often get lost and it is almost impossible to get to the spot I want. 

Also when scrolling the map moves more than I move my finger. 

I am using an OnePlus6

I just wanted you to know...
   

Kind regards!
Carin Landström Olsson

**Comment by dmbfm** [comment]
Hi,

Thanks for the feedback!  

We will be closing the issue for now, since is related to the demo app, but we'll keep it in our internal tracking so we can fix when we work on a new release of the demo.
