### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by aliceengle** [dmbfm/unity-ar-gps-location-issues#55]
Library\PackageCache\com.unity.xr.legacyinputhelpers@2.1.1\Runtime\TrackedPoseDriver\BasePoseProvider.cs(29,17): warning CS1634: Expected disable or restore

device: huawei mate20
unity:2019.3.18
os:android
ar+gps location:Version: 3.4.1

**Comment by dmbfm** [comment]
Hi!

This warning has nothing to do with this asset. It comes from a Unity package... so you should as Unity support about it.
