### ISSUE TITLE
'Logger' does not contain a definition for 'LogFromMethod'

### ISSUE THREAD

**Issue by ThaGlenniator** [dmbfm/unity-ar-gps-location-issues#60]
Assets/ARLocation/Scripts/ARSession/ARFoundationSessionManager.cs(65,20): error CS0117: 'Logger' does not contain a definition for 'LogFromMethod'

I'm using: 
AR + GPS Location 3.4.1
Unity 2019.3.10f1
ARFoundation 4.0.0 preview 3
ARKit XR Plugin 4.0.0 preview 3

**Comment by dmbfm** [comment]
Hi!

I tried to reproduce the error using the same version of unity and ARFoundation/ARKit, but the error did not show up.

If you use a stable version of ARFoundation, e.g., 3, the same error appears?

**Comment by ThaGlenniator** [comment]
Hi Daniel,

Sorry for the late reply. I now started a clean project using ARFoundation 3 and then updated to 4.0.1. All working now :)
Thank you!
