### ISSUE TITLE
heading error

### ISSUE THREAD

**Issue by aliceengle** [dmbfm/unity-ar-gps-location-issues#63]
version: v3.4.1
the function **private void OnCompassUpdatedHandler(HeadingReading newHeading, HeadingReading lastReading)** in **ARLocationOrientation.cs**  have some problem ,

in details,the code

if (isFirstAverage && UseRawUntilFirstAverage)
            {
                
                TrySetOrientation(value, true);
                return;
 
            }
it always change trandform.localRotation in every locationProvider.OnCompassUpdatedEvent ,and not break to the following code

 if (values.Count >= AverageCount)
            {
                if (isFirstAverage)
                {
                    isFirstAverage = false;
                }

                var average = Misc.FloatListAverage(values);
                values.Clear();

                TrySetOrientation(average);
            }

you should delete the code 

if (isFirstAverage && UseRawUntilFirstAverage)
            {
                
                TrySetOrientation(value, true);
                return;
 
            }

**Comment by dmbfm** [comment]
This code is only called if you set `Use Raw Until Firest Average` to true, and only if the firest average is not reached. So it willl change in every update, as long as these conditions are made.

You can just uncheck `Use Raw Until Frist Average`.

Closing this for now

**Comment by aliceengle** [comment]
no,i dont think so.
the problem is that the flag **isFirstAverage**  not set false in run **TrySetOrientation(value, true);**,so next heading event let code repetition run in  "if (isFirstAverage && UseRawUntilFirstAverage)", the flag isFirstAverage not set false sucess after 150 heading.

**Comment by dmbfm** [comment]
Exactly, `isFirstAverage` is only set after the first average is obtained, not the first measurement.  An average is not a single measurement, but needs a series of measurements.
