### ISSUE TITLE
Absolute altitude issues

### ISSUE THREAD

**Issue by silverua** [dmbfm/unity-ar-gps-location-issues#64]
Hi! 
Thanks for the asset! 
I want to use it in an area that has some hills/mountains and the goal is to spawn objects correctly at different altitudes.
We wanted to try to use real altitude from Input.location. Even though you've mentioned that it is not accurate in the docs, just to check how it looks.
I have tried different AltitudeModes, but none of them seem to provide the desired effect. GroundRelative and DeviceRelative work well, but when I place objects, then descend from the hill, the spawned objects still stay on top of the hill. 
With the Absolute mode and location set to 0, I am getting Z coordinate equal to - [some large value like -452302.293084].
Any tips on how to use this properly and how to achieve this effect with hills/mountains to get the points spawned at correct ground level for that particular location with some awareness of real world altitude?

**Comment by dmbfm** [comment]
Hi!

Yes, actually there is an issue with `GroundRelative`  which is causing the effect you see when descending from the hill.  But a fix for that should be out soon, hopefully this week. 

> With the Absolute mode and location set to 0
You are setting the altitude to 0?  Or location to 0?

**Comment by silverua** [comment]
Thanks for responding so quickly! 
My bad, I meant Absolute mode + Altitude set to 0. Does this set of settings mean something like "place points at sea level"?

We made a temp workaround that makes the spawned objects follow the camera in Y axis, so that when we go uphill/downhill the objects follow along with the user. 
But it would be cool if there was some option to place the points more accurately in terms of altitude and not move them when going uphill/downhill.

**Comment by dmbfm** [comment]
Oh, my bad, I read again and I guess I misunderstood what you meant initially. 

Yes, actually, the expected behavior is that objects that are spanned in the hill will stay there. But I will consider adding an option on the next release for that. 

Thanks!
