### ISSUE TITLE
Update path during runtime

### ISSUE THREAD

**Issue by cwule** [dmbfm/unity-ar-gps-location-issues#84]
Is it possible to update the path during runtime?
I saw that it is possible to update the location at runtime, but I would like a solution where a smooth movement path is updated during runtime with new GPS coordinates, so eg. the start of the spline curve is cut and a new part added in the end.

**Comment by dmbfm** [comment]
Hi,

Yes, you can use the `MoveAlongPath.SetLocationPath(LocationPath path)` method. You can get the original path by acessing the property `MoveAlongPath.PathSettings.LocationPath`.

**Comment by cwule** [comment]
Thanks!
