### ISSUE TITLE
basic Loc and Orientation question

### ISSUE THREAD

**Issue by JoergPf** [dmbfm/unity-ar-gps-location-issues#89]
Hi,

I just started with Unity, so sorry for this very basic question:
I successfully installed AR+GPS Location and would like to create a compass that shows the direction and the distance to one object.
What is the best way to access the current location of the user and what is the best way to calculate the direction to the object?

Any hint would be very helpful, thanks for your help!

**Comment by dmbfm** [comment]
Hi,

If you want to calculate the direction to the object, the easiest way is to just the use the World space positions of the objects. I.e., 

`gameObject.transform.position - Camera.main.transform.position`

will give a vector that points from the camera to the game object. To get the direction/unit vector, just normalize this. 

To get the current GPS location just call `ARLocationProvider.CurrentLocation`.

**Comment by JoergPf** [comment]
Great, thanks!

**Comment by JoergPf** [comment]
Hi, sorry for reopening but is there a script/asset that points the user to the capsule in the GPS Stage Object? 
A bit like this one https://miro.medium.com/max/1400/1*tEa8RUrdQs1Rk9pX2lo7vQ.jpeg or the debugLine you are showing.

Thanks for your help!

**Comment by dmbfm** [comment]
Hi!

Currently we just have the script that creates the Debug Line, but you can probably copy and modify it to suit your needs. It is located at `ARLocation\Scripts\Components\UI\DebugDistance.cs`. Let me know if you need any help with that, thanks!
