### ISSUE TITLE
Build errors (ARCore) during first basic build following tutorial

### ISSUE THREAD

**Issue by Siggytron** [dmbfm/unity-ar-gps-location-issues#92]
Followed your youtube  instructions on a new build in version 2019.4.9f1. Device is approved: Motorola g7 power.

I get "Manifest merger failed with multiple errors, see logs" and a bunch of errors, which I will list below. 

Errors:

[:arcore_client:] C:\Users\Serena\.gradle\caches\transforms-2\files-2.1\8335ef17e078d4278b40607ce42761c4\AndroidManifest.xml:30:9-54 Error:

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
---------------------------------------------------------------------------------------------------------------------------
	Missing 'package' key attribute on element package at [:arcore_client:] AndroidManifest.xml:30:9-54

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-----------------------------------------------------------------------------------------------------------------------------
[:arcore_client:] C:\Users\Serena\.gradle\caches\transforms-2\files-2.1\8335ef17e078d4278b40607ce42761c4\AndroidManifest.xml Error:

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-----------------------------------------------------------------------------------------------------------------------------
	Validation failed, exiting

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-----------------------------------------------------------------------------------------------------------------------------
FAILURE: Build failed with an exception.

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-----------------------------------------------------------------------------------------------------------------------------
* What went wrong:

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
--------------------------------------------------------------------------------------------------------------------------------
Execution failed for task ':launcher:processReleaseManifest'.

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
----------------------------------------------------------------------------------------------------------------------------------
> Manifest merger failed with multiple errors, see logs

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
--------------------------------------------------------------------------------------------------------------------------------
 * Try:

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
-----------------------------------------------------------------------------------------------------------------------------
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Unity Version: 2019.4.f1
ARFoundation version 2.1.10
ARSubsystems version 2.1.3
ARCore version 2.1.12

**Smartphone (please complete the following information):**
 - Device: Motorola g7 power
 - OS: Android Oreo 
 - Version: 26

**Additional context**
By the way, I accidentally did a build forgetting to install ARCore and I got no errors BUT the build didn't work of course. I just got a black screen. So ARFoundation without ARCore = no errors.  ARFoundation with ARCore = errors.

**Comment by dmbfm** [comment]
Have you tried other combinations of AR Foundation/AR Core versions?

These error occur only when the AR+GPS asset is imported, or do you also get them even without AR+GPS? If so, I would advise you to reach out for Unity support regarding this, since it seems to be a build error related to their packates (AR Foundation/AR Core).

Sometimes with these android build errors, for some reason, creating a new empty project or even reinstalling the Unity editor, makes them go away.

**Comment by Siggytron** [comment]
I did try ARCore 4.1 but I got the same errors. Were you able to access my zipped project?

**Comment by Siggytron** [comment]
Okay! I made a new project and I set the ARCore to an EARLIER version and it finally worked. Hallelujah.  The version I used that finally worked was ARCore 2.0.2.   (The version that Unity 2019.4.9f1 defaults to is 2.1.12. That's the one that gets the title 'verified.)  So if you get other people using ARCore with gradle problems, you could suggest trying ARCore 2.0.2.

Phew!
